title: Molly Stroud
email: mollystroud@vt.edu
description: >- # this means to ignore newlines until "baseurl:"
  Remote sensing hydrologist
baseurl: ""
icon: /assets/images/icon-512.png
# Build settings
markdown: kramdown
